### ISSUE TITLE
ldoc.css is missing

### ISSUE THREAD

**Issue by mpeterv** [Yonaba/strictness#5]
Hello! The style sheet for the documentation(`ldoc.css`) is missing from the `doc` directory, which makes it (documentation) look ugly. E.g. try running `luarocks doc strictness`. Perhaps [this](https://github.com/Yonaba/strictness/blob/d68a4c23faed6bdc106d4dea36d746fde6f66fbc/.gitignore#L4) line could be tweaked so that `doc/ldoc.css` is not ignored.

**Comment by Yonaba** [comment]
@mpeterv, would you mind submitting a PR ?
